// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/job/job.proto

package job

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AsyncSubmitRequest struct {
	// job名称
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name"`
	// job类型,回调通知时根据job类型执行不同的操作
	Type string `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type"`
	// 插件集合
	PluginSet []string `protobuf:"bytes,3,rep,name=PluginSet,proto3" json:"PluginSet"`
	// job数据
	Data string `protobuf:"bytes,4,opt,name=Data,proto3" json:"Data"`
	// job完成是否需要通知worker
	IsNotify bool `protobuf:"varint,5,opt,name=IsNotify,proto3" json:"IsNotify"`
	// job标签，便于job快速搜索
	Label string `protobuf:"bytes,6,opt,name=Label,proto3" json:"Label"`
	// 数据来源，提交job的应用名称
	Source               string   `protobuf:"bytes,7,opt,name=Source,proto3" json:"Source"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsyncSubmitRequest) Reset()         { *m = AsyncSubmitRequest{} }
func (m *AsyncSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*AsyncSubmitRequest) ProtoMessage()    {}
func (*AsyncSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60868841c20a44, []int{0}
}

func (m *AsyncSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsyncSubmitRequest.Unmarshal(m, b)
}
func (m *AsyncSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsyncSubmitRequest.Marshal(b, m, deterministic)
}
func (m *AsyncSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncSubmitRequest.Merge(m, src)
}
func (m *AsyncSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_AsyncSubmitRequest.Size(m)
}
func (m *AsyncSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncSubmitRequest proto.InternalMessageInfo

func (m *AsyncSubmitRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AsyncSubmitRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AsyncSubmitRequest) GetPluginSet() []string {
	if m != nil {
		return m.PluginSet
	}
	return nil
}

func (m *AsyncSubmitRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *AsyncSubmitRequest) GetIsNotify() bool {
	if m != nil {
		return m.IsNotify
	}
	return false
}

func (m *AsyncSubmitRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AsyncSubmitRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type AsyncSubmitResponse struct {
	// job ID需要记录
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsyncSubmitResponse) Reset()         { *m = AsyncSubmitResponse{} }
func (m *AsyncSubmitResponse) String() string { return proto.CompactTextString(m) }
func (*AsyncSubmitResponse) ProtoMessage()    {}
func (*AsyncSubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60868841c20a44, []int{1}
}

func (m *AsyncSubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsyncSubmitResponse.Unmarshal(m, b)
}
func (m *AsyncSubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsyncSubmitResponse.Marshal(b, m, deterministic)
}
func (m *AsyncSubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncSubmitResponse.Merge(m, src)
}
func (m *AsyncSubmitResponse) XXX_Size() int {
	return xxx_messageInfo_AsyncSubmitResponse.Size(m)
}
func (m *AsyncSubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncSubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncSubmitResponse proto.InternalMessageInfo

func (m *AsyncSubmitResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AsyncNotifyRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// job名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name"`
	// job类型,异步回调通知时使用，根据不同值执行对应业务
	Type string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type"`
	// job状态,2：执行完成，3：取消执行，4：系统异常，5：task推送失败，6：运行超时，7：业务处理异常，8：回调通知异常
	Status int32 `protobuf:"varint,4,opt,name=Status,proto3" json:"Status"`
	// 结果输出
	Result string `protobuf:"bytes,5,opt,name=Result,proto3" json:"Result"`
	// 异常信息
	Mesage               string   `protobuf:"bytes,6,opt,name=Mesage,proto3" json:"Mesage"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsyncNotifyRequest) Reset()         { *m = AsyncNotifyRequest{} }
func (m *AsyncNotifyRequest) String() string { return proto.CompactTextString(m) }
func (*AsyncNotifyRequest) ProtoMessage()    {}
func (*AsyncNotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60868841c20a44, []int{2}
}

func (m *AsyncNotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsyncNotifyRequest.Unmarshal(m, b)
}
func (m *AsyncNotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsyncNotifyRequest.Marshal(b, m, deterministic)
}
func (m *AsyncNotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsyncNotifyRequest.Merge(m, src)
}
func (m *AsyncNotifyRequest) XXX_Size() int {
	return xxx_messageInfo_AsyncNotifyRequest.Size(m)
}
func (m *AsyncNotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AsyncNotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AsyncNotifyRequest proto.InternalMessageInfo

func (m *AsyncNotifyRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AsyncNotifyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AsyncNotifyRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AsyncNotifyRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AsyncNotifyRequest) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *AsyncNotifyRequest) GetMesage() string {
	if m != nil {
		return m.Mesage
	}
	return ""
}

type SyncSubmitRequest struct {
	// job名称
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name"`
	// 插件集合
	PluginSet []string `protobuf:"bytes,2,rep,name=PluginSet,proto3" json:"PluginSet"`
	// job数据
	Data string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data"`
	// job标签，便于job快速搜索
	Label string `protobuf:"bytes,4,opt,name=Label,proto3" json:"Label"`
	// 数据来源，提交job的应用名称
	Source               string   `protobuf:"bytes,5,opt,name=Source,proto3" json:"Source"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncSubmitRequest) Reset()         { *m = SyncSubmitRequest{} }
func (m *SyncSubmitRequest) String() string { return proto.CompactTextString(m) }
func (*SyncSubmitRequest) ProtoMessage()    {}
func (*SyncSubmitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60868841c20a44, []int{3}
}

func (m *SyncSubmitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncSubmitRequest.Unmarshal(m, b)
}
func (m *SyncSubmitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncSubmitRequest.Marshal(b, m, deterministic)
}
func (m *SyncSubmitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncSubmitRequest.Merge(m, src)
}
func (m *SyncSubmitRequest) XXX_Size() int {
	return xxx_messageInfo_SyncSubmitRequest.Size(m)
}
func (m *SyncSubmitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncSubmitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncSubmitRequest proto.InternalMessageInfo

func (m *SyncSubmitRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SyncSubmitRequest) GetPluginSet() []string {
	if m != nil {
		return m.PluginSet
	}
	return nil
}

func (m *SyncSubmitRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *SyncSubmitRequest) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *SyncSubmitRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type SyncSubmitResponse struct {
	// job ID
	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id"`
	// job状态,0:待执行，1：执行中，2：执行完成，3：取消执行，4：系统异常，5：推送失败，6：运行超时，7：业务处理异常
	Status int32 `protobuf:"varint,2,opt,name=Status,proto3" json:"Status"`
	// 处理结果
	Result string `protobuf:"bytes,3,opt,name=Result,proto3" json:"Result"`
	// 异常信息
	Mesage               string   `protobuf:"bytes,6,opt,name=Mesage,proto3" json:"Mesage"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncSubmitResponse) Reset()         { *m = SyncSubmitResponse{} }
func (m *SyncSubmitResponse) String() string { return proto.CompactTextString(m) }
func (*SyncSubmitResponse) ProtoMessage()    {}
func (*SyncSubmitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60868841c20a44, []int{4}
}

func (m *SyncSubmitResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncSubmitResponse.Unmarshal(m, b)
}
func (m *SyncSubmitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncSubmitResponse.Marshal(b, m, deterministic)
}
func (m *SyncSubmitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncSubmitResponse.Merge(m, src)
}
func (m *SyncSubmitResponse) XXX_Size() int {
	return xxx_messageInfo_SyncSubmitResponse.Size(m)
}
func (m *SyncSubmitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncSubmitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncSubmitResponse proto.InternalMessageInfo

func (m *SyncSubmitResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SyncSubmitResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SyncSubmitResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *SyncSubmitResponse) GetMesage() string {
	if m != nil {
		return m.Mesage
	}
	return ""
}

func init() {
	proto.RegisterType((*AsyncSubmitRequest)(nil), "job.AsyncSubmitRequest")
	proto.RegisterType((*AsyncSubmitResponse)(nil), "job.AsyncSubmitResponse")
	proto.RegisterType((*AsyncNotifyRequest)(nil), "job.AsyncNotifyRequest")
	proto.RegisterType((*SyncSubmitRequest)(nil), "job.SyncSubmitRequest")
	proto.RegisterType((*SyncSubmitResponse)(nil), "job.SyncSubmitResponse")
}

func init() { proto.RegisterFile("proto/job/job.proto", fileDescriptor_4f60868841c20a44) }

var fileDescriptor_4f60868841c20a44 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x8a, 0xdb, 0x30,
	0x10, 0xc6, 0x76, 0x9c, 0xc6, 0x13, 0x5a, 0xa8, 0x52, 0x12, 0xe1, 0xf6, 0x10, 0x0c, 0x05, 0x9f,
	0x6c, 0x68, 0xef, 0x2d, 0x0d, 0xed, 0x21, 0xa5, 0x0d, 0x45, 0xee, 0x69, 0x6f, 0x76, 0xa2, 0x18,
	0x07, 0x27, 0xf2, 0x46, 0xf2, 0x82, 0x9f, 0x60, 0x5f, 0x60, 0x1f, 0x66, 0x5f, 0x63, 0xdf, 0x68,
	0x91, 0xfc, 0x13, 0x7b, 0x9d, 0xb0, 0x39, 0x18, 0xe6, 0xfb, 0xac, 0x91, 0xe6, 0xfb, 0x66, 0x06,
	0x26, 0xd9, 0x91, 0x09, 0xe6, 0xef, 0x58, 0x24, 0x3f, 0x4f, 0x21, 0x64, 0xec, 0x58, 0x64, 0x7f,
	0x8c, 0x19, 0x8b, 0x53, 0xea, 0x2b, 0x2a, 0xca, 0xb7, 0x3e, 0xdd, 0x67, 0xa2, 0x28, 0x4f, 0x38,
	0x8f, 0x1a, 0xa0, 0x1f, 0xbc, 0x38, 0xac, 0x83, 0x3c, 0xda, 0x27, 0x82, 0xd0, 0xdb, 0x9c, 0x72,
	0x81, 0x10, 0x0c, 0x56, 0xe1, 0x9e, 0x62, 0x6d, 0xae, 0xb9, 0x16, 0x51, 0xb1, 0xe4, 0xfe, 0x17,
	0x19, 0xc5, 0x7a, 0xc9, 0xc9, 0x18, 0x7d, 0x02, 0xeb, 0x5f, 0x9a, 0xc7, 0xc9, 0x21, 0xa0, 0x02,
	0x1b, 0x73, 0xc3, 0xb5, 0xc8, 0x89, 0x90, 0x19, 0x3f, 0x43, 0x11, 0xe2, 0x41, 0x99, 0x21, 0x63,
	0x64, 0xc3, 0x68, 0xc9, 0x57, 0x4c, 0x24, 0xdb, 0x02, 0x9b, 0x73, 0xcd, 0x1d, 0x91, 0x06, 0xa3,
	0x0f, 0x60, 0xfe, 0x09, 0x23, 0x9a, 0xe2, 0xa1, 0x4a, 0x28, 0x01, 0x9a, 0xc2, 0x30, 0x60, 0xf9,
	0x71, 0x4d, 0xf1, 0x1b, 0x45, 0x57, 0xc8, 0xf9, 0x0c, 0x93, 0x4e, 0xe5, 0x3c, 0x63, 0x07, 0x4e,
	0xd1, 0x3b, 0xd0, 0x97, 0x1b, 0x55, 0xb8, 0x41, 0xf4, 0xe5, 0xc6, 0x79, 0xa8, 0x15, 0x96, 0x8f,
	0xd4, 0x0a, 0x5f, 0x1c, 0x6b, 0x14, 0xeb, 0x67, 0x14, 0x1b, 0x2d, 0xc5, 0xb2, 0x1a, 0x11, 0x8a,
	0x9c, 0x2b, 0x55, 0x26, 0xa9, 0x90, 0xe4, 0x09, 0xe5, 0x79, 0x2a, 0x94, 0x2a, 0x8b, 0x54, 0x48,
	0xf2, 0x7f, 0x29, 0x0f, 0x63, 0x5a, 0x89, 0xaa, 0x90, 0x73, 0xaf, 0xc1, 0xfb, 0xe0, 0x2a, 0xdf,
	0x3b, 0x1e, 0xeb, 0x97, 0x3c, 0x36, 0x5a, 0x1e, 0x37, 0x3e, 0x0e, 0xce, 0xfb, 0x68, 0x76, 0x7c,
	0x4c, 0x01, 0x05, 0xaf, 0xda, 0xd8, 0xd2, 0xad, 0x5f, 0xd0, 0x6d, 0x5c, 0xa3, 0xfb, 0xcb, 0x93,
	0x06, 0xf0, 0x9b, 0x45, 0x01, 0x3d, 0xde, 0x25, 0x6b, 0x8a, 0x16, 0x30, 0x6e, 0x35, 0x11, 0xcd,
	0x3c, 0x39, 0xbc, 0xfd, 0x81, 0xb4, 0x71, 0xff, 0x47, 0x59, 0xa8, 0xab, 0xa1, 0x6f, 0xd5, 0x1d,
	0xd5, 0x14, 0xb5, 0xee, 0xe8, 0xb4, 0xdc, 0x9e, 0x7a, 0xe5, 0x26, 0x78, 0xf5, 0x26, 0x78, 0xbf,
	0xe4, 0x26, 0xa0, 0xef, 0x00, 0x27, 0x03, 0xd0, 0x54, 0xa5, 0xf7, 0x5a, 0x63, 0xcf, 0x7a, 0x7c,
	0x5d, 0xc0, 0xe2, 0xed, 0xcd, 0xd8, 0xf3, 0x9b, 0xfd, 0x8b, 0x86, 0x2a, 0xfc, 0xfa, 0x1c, 0x00,
	0x00, 0xff, 0xff, 0x83, 0x38, 0xcc, 0xa7, 0x93, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	// 异步提交job
	AsyncSubmit(ctx context.Context, opts ...grpc.CallOption) (JobService_AsyncSubmitClient, error)
	// 异步通知
	AsyncNotify(ctx context.Context, in *AsyncNotifyRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// 同步提交job(当调度器挂掉会导致job处理中断，谨用)
	SyncSubmit(ctx context.Context, opts ...grpc.CallOption) (JobService_SyncSubmitClient, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) AsyncSubmit(ctx context.Context, opts ...grpc.CallOption) (JobService_AsyncSubmitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobService_serviceDesc.Streams[0], "/job.JobService/AsyncSubmit", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobServiceAsyncSubmitClient{stream}
	return x, nil
}

type JobService_AsyncSubmitClient interface {
	Send(*AsyncSubmitRequest) error
	CloseAndRecv() (*AsyncSubmitResponse, error)
	grpc.ClientStream
}

type jobServiceAsyncSubmitClient struct {
	grpc.ClientStream
}

func (x *jobServiceAsyncSubmitClient) Send(m *AsyncSubmitRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *jobServiceAsyncSubmitClient) CloseAndRecv() (*AsyncSubmitResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AsyncSubmitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobServiceClient) AsyncNotify(ctx context.Context, in *AsyncNotifyRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/job.JobService/AsyncNotify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobServiceClient) SyncSubmit(ctx context.Context, opts ...grpc.CallOption) (JobService_SyncSubmitClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobService_serviceDesc.Streams[1], "/job.JobService/SyncSubmit", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobServiceSyncSubmitClient{stream}
	return x, nil
}

type JobService_SyncSubmitClient interface {
	Send(*SyncSubmitRequest) error
	CloseAndRecv() (*SyncSubmitResponse, error)
	grpc.ClientStream
}

type jobServiceSyncSubmitClient struct {
	grpc.ClientStream
}

func (x *jobServiceSyncSubmitClient) Send(m *SyncSubmitRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *jobServiceSyncSubmitClient) CloseAndRecv() (*SyncSubmitResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SyncSubmitResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	// 异步提交job
	AsyncSubmit(JobService_AsyncSubmitServer) error
	// 异步通知
	AsyncNotify(context.Context, *AsyncNotifyRequest) (*empty.Empty, error)
	// 同步提交job(当调度器挂掉会导致job处理中断，谨用)
	SyncSubmit(JobService_SyncSubmitServer) error
}

// UnimplementedJobServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJobServiceServer struct {
}

func (*UnimplementedJobServiceServer) AsyncSubmit(srv JobService_AsyncSubmitServer) error {
	return status.Errorf(codes.Unimplemented, "method AsyncSubmit not implemented")
}
func (*UnimplementedJobServiceServer) AsyncNotify(ctx context.Context, req *AsyncNotifyRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsyncNotify not implemented")
}
func (*UnimplementedJobServiceServer) SyncSubmit(srv JobService_SyncSubmitServer) error {
	return status.Errorf(codes.Unimplemented, "method SyncSubmit not implemented")
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_AsyncSubmit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JobServiceServer).AsyncSubmit(&jobServiceAsyncSubmitServer{stream})
}

type JobService_AsyncSubmitServer interface {
	SendAndClose(*AsyncSubmitResponse) error
	Recv() (*AsyncSubmitRequest, error)
	grpc.ServerStream
}

type jobServiceAsyncSubmitServer struct {
	grpc.ServerStream
}

func (x *jobServiceAsyncSubmitServer) SendAndClose(m *AsyncSubmitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *jobServiceAsyncSubmitServer) Recv() (*AsyncSubmitRequest, error) {
	m := new(AsyncSubmitRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _JobService_AsyncNotify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsyncNotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).AsyncNotify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.JobService/AsyncNotify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).AsyncNotify(ctx, req.(*AsyncNotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobService_SyncSubmit_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JobServiceServer).SyncSubmit(&jobServiceSyncSubmitServer{stream})
}

type JobService_SyncSubmitServer interface {
	SendAndClose(*SyncSubmitResponse) error
	Recv() (*SyncSubmitRequest, error)
	grpc.ServerStream
}

type jobServiceSyncSubmitServer struct {
	grpc.ServerStream
}

func (x *jobServiceSyncSubmitServer) SendAndClose(m *SyncSubmitResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *jobServiceSyncSubmitServer) Recv() (*SyncSubmitRequest, error) {
	m := new(SyncSubmitRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AsyncNotify",
			Handler:    _JobService_AsyncNotify_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AsyncSubmit",
			Handler:       _JobService_AsyncSubmit_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SyncSubmit",
			Handler:       _JobService_SyncSubmit_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/job/job.proto",
}
