// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/node/node.proto

package node

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMasterResponse struct {
	NodeInfo             *NodeInfo `protobuf:"bytes,1,opt,name=NodeInfo,proto3" json:"NodeInfo"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetMasterResponse) Reset()         { *m = GetMasterResponse{} }
func (m *GetMasterResponse) String() string { return proto.CompactTextString(m) }
func (*GetMasterResponse) ProtoMessage()    {}
func (*GetMasterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b558ce09c246314, []int{0}
}

func (m *GetMasterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMasterResponse.Unmarshal(m, b)
}
func (m *GetMasterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMasterResponse.Marshal(b, m, deterministic)
}
func (m *GetMasterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMasterResponse.Merge(m, src)
}
func (m *GetMasterResponse) XXX_Size() int {
	return xxx_messageInfo_GetMasterResponse.Size(m)
}
func (m *GetMasterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMasterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMasterResponse proto.InternalMessageInfo

func (m *GetMasterResponse) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

type NodeInfo struct {
	// 服务器地址
	Endpoint string `protobuf:"bytes,1,opt,name=Endpoint,proto3" json:"Endpoint"`
	// 节点ID
	NodeId               string   `protobuf:"bytes,2,opt,name=NodeId,proto3" json:"NodeId"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b558ce09c246314, []int{1}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *NodeInfo) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type HeartBeatRequest struct {
	NodeInfo *NodeInfo `protobuf:"bytes,1,opt,name=NodeInfo,proto3" json:"NodeInfo"`
	// worker节点所有支持的插件
	PluginSet            []string `protobuf:"bytes,2,rep,name=PluginSet,proto3" json:"PluginSet"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRequest) Reset()         { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()    {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b558ce09c246314, []int{2}
}

func (m *HeartBeatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRequest.Unmarshal(m, b)
}
func (m *HeartBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRequest.Marshal(b, m, deterministic)
}
func (m *HeartBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequest.Merge(m, src)
}
func (m *HeartBeatRequest) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRequest.Size(m)
}
func (m *HeartBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequest proto.InternalMessageInfo

func (m *HeartBeatRequest) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *HeartBeatRequest) GetPluginSet() []string {
	if m != nil {
		return m.PluginSet
	}
	return nil
}

func init() {
	proto.RegisterType((*GetMasterResponse)(nil), "node.GetMasterResponse")
	proto.RegisterType((*NodeInfo)(nil), "node.NodeInfo")
	proto.RegisterType((*HeartBeatRequest)(nil), "node.HeartBeatRequest")
}

func init() { proto.RegisterFile("proto/node/node.proto", fileDescriptor_2b558ce09c246314) }

var fileDescriptor_2b558ce09c246314 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0xcb, 0x4f, 0x49, 0x05, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0x2d, 0x25,
	0x9d, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x0f, 0x16, 0x4b, 0x2a, 0x4d, 0xd3, 0x4f, 0xcd, 0x2d,
	0x28, 0xa9, 0x84, 0x28, 0x51, 0xb2, 0xe7, 0x12, 0x74, 0x4f, 0x2d, 0xf1, 0x4d, 0x2c, 0x2e, 0x49,
	0x2d, 0x0a, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0xd2, 0xe2, 0xe2, 0xf0, 0xcb, 0x4f,
	0x49, 0xf5, 0xcc, 0x4b, 0xcb, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd3, 0x03, 0x1b,
	0x0b, 0x13, 0x0d, 0x82, 0xcb, 0x2b, 0xd9, 0x21, 0xd4, 0x0a, 0x49, 0x71, 0x71, 0xb8, 0xe6, 0xa5,
	0x14, 0xe4, 0x67, 0xe6, 0x95, 0x80, 0xf5, 0x71, 0x06, 0xc1, 0xf9, 0x42, 0x62, 0x5c, 0x6c, 0x60,
	0x75, 0x29, 0x12, 0x4c, 0x60, 0x19, 0x28, 0x4f, 0x29, 0x86, 0x4b, 0xc0, 0x23, 0x35, 0xb1, 0xa8,
	0xc4, 0x29, 0x35, 0xb1, 0x24, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x84, 0x14, 0xfb, 0x85, 0x64,
	0xb8, 0x38, 0x03, 0x72, 0x4a, 0xd3, 0x33, 0xf3, 0x82, 0x53, 0x4b, 0x24, 0x98, 0x14, 0x98, 0x35,
	0x38, 0x83, 0x10, 0x02, 0x46, 0x1d, 0x8c, 0x5c, 0xdc, 0x20, 0xa5, 0xc1, 0xa9, 0x45, 0x65, 0x99,
	0xc9, 0xa9, 0x42, 0x36, 0x5c, 0x9c, 0x70, 0xef, 0x0a, 0x89, 0xe9, 0x41, 0x42, 0x46, 0x0f, 0x16,
	0x32, 0x7a, 0xae, 0xa0, 0x90, 0x91, 0x12, 0x87, 0x58, 0x86, 0x19, 0x2e, 0xd6, 0x5c, 0x9c, 0x70,
	0xb7, 0x0a, 0x89, 0x41, 0x54, 0xa1, 0x3b, 0x5e, 0x0a, 0x87, 0xa9, 0x49, 0x6c, 0x60, 0xbe, 0x31,
	0x20, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xb9, 0x8f, 0x6a, 0xac, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeServiceClient interface {
	// 获取主节点信息
	GetMaster(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetMasterResponse, error)
	// 心跳检测
	HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type nodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeServiceClient(cc *grpc.ClientConn) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) GetMaster(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetMasterResponse, error) {
	out := new(GetMasterResponse)
	err := c.cc.Invoke(ctx, "/node.NodeService/GetMaster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) HeartBeat(ctx context.Context, in *HeartBeatRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/node.NodeService/HeartBeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
type NodeServiceServer interface {
	// 获取主节点信息
	GetMaster(context.Context, *empty.Empty) (*GetMasterResponse, error)
	// 心跳检测
	HeartBeat(context.Context, *HeartBeatRequest) (*empty.Empty, error)
}

// UnimplementedNodeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (*UnimplementedNodeServiceServer) GetMaster(ctx context.Context, req *empty.Empty) (*GetMasterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaster not implemented")
}
func (*UnimplementedNodeServiceServer) HeartBeat(ctx context.Context, req *HeartBeatRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_GetMaster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetMaster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.NodeService/GetMaster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetMaster(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_HeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartBeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).HeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/node.NodeService/HeartBeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).HeartBeat(ctx, req.(*HeartBeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "node.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMaster",
			Handler:    _NodeService_GetMaster_Handler,
		},
		{
			MethodName: "HeartBeat",
			Handler:    _NodeService_HeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/node/node.proto",
}
